import { Router } from 'express';
import { authRouter } from './modules/auth/auth.routes';
import { userRouter } from './modules/users/users.routes';
import { jobRouter } from './modules/jobs/jobs.routes';
import { companyRouter } from './modules/jobs/companies.routes';
import { postRouter } from './modules/posts/posts.routes';
import { chatRouter } from './modules/chat/chat.routes';
import { communityRouter } from './modules/communities/communities.routes';
import { notificationRouter } from './modules/notifications/notifications.routes';
import { cvRouter } from './modules/cv/cv.routes';
import { aiRouter } from './modules/ai/ai.routes';
import { mediaRouter } from './modules/media/media.routes';
import { analyzerRouter } from './modules/cv-analyzer/analyzer.routes';
import { interviewRouter } from './modules/interview/interview.routes';
import { matchRouter } from './modules/match/match.routes';
import { gamificationRouter } from './modules/gamification/gamification.routes';
import { freelanceRouter } from './modules/freelance/freelance.routes';
import { eventRouter } from './modules/events/events.routes';
import { roadmapRouter } from './modules/roadmap/roadmap.routes';
import { trendingRouter } from './modules/trending/trending.routes';
import { homeRouter } from './modules/home/home.routes';
import { searchRouter } from './modules/search/search.routes';
import { coachRouter } from './modules/coach/coach.routes';
import { projectsRouter } from './modules/projects/projects.routes';
import { digestRouter } from './modules/digest/digest.routes';

export const router = Router();
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/jobs', jobRouter);
router.use('/companies', companyRouter);
router.use('/posts', postRouter);
router.use('/chat', chatRouter);
router.use('/communities', communityRouter);
router.use('/notifications', notificationRouter);
router.use('/cv', cvRouter);
router.use('/ai', aiRouter);
router.use('/media', mediaRouter);
router.use('/cv-analyzer', analyzerRouter);
router.use('/interview', interviewRouter);
router.use('/match', matchRouter);
router.use('/gamification', gamificationRouter);
router.use('/freelance', freelanceRouter);
router.use('/events', eventRouter);
router.use('/roadmap', roadmapRouter);
router.use('/trending', trendingRouter);
router.use('/home', homeRouter);
router.use('/search', searchRouter);
router.use('/coach', coachRouter);
router.use('/projects', projectsRouter);
router.use('/digest', digestRouter);
